//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mozhina.Nsudotnet.Rss2Email.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Rss2Email : global::System.Configuration.ApplicationSettingsBase {
        
        private static Rss2Email defaultInstance = ((Rss2Email)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Rss2Email())));
        
        public static Rss2Email Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime lastCheck {
            get {
                return ((global::System.DateTime)(this["lastCheck"]));
            }
            set {
                this["lastCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime lastSent {
            get {
                return ((global::System.DateTime)(this["lastSent"]));
            }
            set {
                this["lastSent"] = value;
            }
        }
    }
}
