#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Mail/ItemView.cshtml")]
    public partial class _Views_Mail_ItemView_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Mail_ItemView_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<a");

WriteAttribute("href", Tuple.Create(" href=\"", 2), Tuple.Create("\"", 20)
            
            #line 1 "..\..\Views\Mail\ItemView.cshtml"
, Tuple.Create(Tuple.Create("", 9), Tuple.Create<System.Object, System.Int32>(Model.Link
            
            #line default
            #line hidden
, 9), false)
);

WriteLiteral(">");

            
            #line 1 "..\..\Views\Mail\ItemView.cshtml"
                 Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n<br>\r\n");

            
            #line 3 "..\..\Views\Mail\ItemView.cshtml"
Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n<br>");

        }
    }
}
#pragma warning restore 1591
